### ISSUE TITLE
How to deal with templated ctl

### ISSUE THREAD

**Issue by royalosyin** [miniufo/xgrads#1]
It is an excellent package. 
However, how to deal with templated ctl with many individual files?

**Comment by miniufo** [comment]
Actually I do not have many chances to deal with the template case.  But I think it is possible to implement this functionality similar to xarray's [open_mfdataset](http://xarray.pydata.org/en/stable/generated/xarray.open_mfdataset.html).

Could you please send me a minimum template ctl and corresponding binary files (Email: miniufo@163.com) if you have.  I would like a try to enhance that.

**Comment by royalosyin** [comment]
I used the APHRODITE Japan precipitation, where the data is saved year by year. The data is too big to send to you. The ctl file (AphroJP_V1207_DPREC.CSTN.ctl) looks like:
====================================================
DSET        ^AphroJP_V1207_DPREC.CSTN.%y4
UNDEF       -99.9
OPTIONS     little_endian template
TITLE       APHRO_JP V1207 daily precipitation
XDEF   460  LINEAR   123.025 0.05 
YDEF   440  LINEAR    24.025 0.05
ZDEF    01  LEVELS   1
TDEF 42000  LINEAR   01JAN1900 1dy 
VARS     1        
precip      1 00 daily precipitation (mm/day)   
ENDVARS
====================================================
xgrads can parse the ctl file, however it is hard to find the corresponding data files.
It took the AphroJP_V1207_DPREC.CSTN.%y4 as the data file name, and so fail to parse the %y4.

**Comment by miniufo** [comment]
Hi @royalosyin , I just update some codes to support the template parsing and reading.  Some template datasets (test8.ctl and test9.ctl) are generated from `dset = xarray.tutorial.open_dataset('air_temperature')` in the `ctls` folder.  I've succeed in parsing and reading these datasets on my PC.

Would you please give a try using your precipitation dataset and tell me if it works out OK?  Right now not all the template formats are supported.  Only those I understand are supported.  But this may be improved in the future if there are huge demands.

**Comment by royalosyin** [comment]
Hi @miniufo, thanks for updating.  
I test the new version. It works now.
