### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'tslb'

### ISSUE THREAD

**Issue by cjj920** [miniufo/xgrads#14]
I owe a debt of thanks to your wonderful module helping me a lot. but i had the following error while reading my ctl file:

> Traceback (most recent call last):
  File "main.py", line 34, in <module>
    data    =  DR.dataread(ctlpath)
  File "/mnt/e/WNP/grd/dataread.py", line 19, in dataread
    dset = open_CtlDataset(ctlpath)
  File "/home/jean/anaconda3/lib/python3.8/site-packages/xgrads/io.py", line 102, in open_CtlDataset
    ctl = CtlDescriptor(encoding=encoding, file=desfile)
  File "/home/jean/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 137, in __init__
    self.parse(fileContent)
  File "/home/jean/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 178, in parse
    self._processVars(oneline, fileContent)
  File "/home/jean/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 404, in _processVars
    v  = CtlVar(fileContent[start+i])
  File "/home/jean/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 789, in __init__
    self.zcount = int(self.zcount)
ValueError: invalid literal for int() with base 10: 'tslb'

and I found that the error originated with a blank space in front of the variable 'tslb' in the my ctl file. The code works successfully when I remove this space in the ctl file.  Is there any way to read data successfully without modifying ctl file？

**Comment by miniufo** [comment]
Would you please send me your ctl file or just paste its content here?  I think a simple `strip()` call for each line would be a quick solution.

**Comment by cjj920** [comment]
Thank you for taking time to answer my question, and this is my ctl file. 
I read binary data file using open_CtlDataset('post2019080806.ctl') simply. I'm so sorry that i didn't understand how to use strip()for each line? Should i modify the source code?




-------------------------------------------------------
On 8/17/2020 09:00，Yu-Kun Qian<notifications@github.com> wrote：

Would you please send me your ctl file or just paste its content here? I think a simple strip() call for each line would be a quick solution.

**Comment by miniufo** [comment]
Would you paste the content of your ctl file (not just the file name post2019080806.ctl) here so that I can quickly find the problem?

**Comment by cjj920** [comment]
i am sorry you did not see the ctl file as a attachment i sent. the follwing is my ctl file
> dset ^postvar2019080800
options sequential big_endian
title post output from grapes
undef -9.99E+33
xdef   601  linear    90.9000    0.1000
ydef   601  linear    -7.3000    0.1000
zdef   26 levels 
   1000.000    
   975.0000    
   950.0000    
   925.0000    
   900.0000    
   850.0000    
   800.0000    
   750.0000    
   700.0000    
   650.0000    
   600.0000    
   550.0000    
   500.0000    
   450.0000    
   400.0000    
   350.0000    
   300.0000    
   250.0000    
   200.0000    
   150.0000    
   100.0000    
   70.00000    
   50.00000    
   30.00000    
   20.00000    
   10.00000    
tdef   25 linear 00z08AUG2019   180mn
vars 38
u 26 0 u_wind
v 26 0 v_wind
t 26 0 temperature
h 26 0 geopotential height
Qv 26 0 Q vapor
Qc 26 0 Q cloud
Qr 26 0 Q rain
Qi 26 0 Q ice
Qs 26 0 Q snow
Qg 26 0 Q grapaul
w 26 0 vertical wind
ps 0 0 surface pressure
psl 0 0 sea level pressure
rainc 0 0 precipitation
rainnc 0 0 precipitation
ts 0 0 surface temperature
glw 0 0 surface long wave radiation flux
gsw 0 0 surface short wave radiation flux
hfx 0 0 surface heat flux
qfx 0 0 surface vapour flux
q2m 0 0 vapour at 2m
t2m 0 0 t at 2m
u10m 0 0 u at 10m
v10m 0 0 v at 10m
lu 0 0 land use
znt 0 0 roughness
emiss 0 0 vegetation type
alvsf 0 0 mean vis albedo 1
alnsf 0 0 mean nir albedo 1
alvwf 0 0 mean vis albedo 2
alnwf 0 0 mean nir albedo 2
facsf 0 0 strong cosz dependency
facwf 0 0 weak cosz dependency
snowh 0 0 soil type
zs 0 0 terrain
tmn 0 0 tmn
 tslb            4  0 tslb
 mslb            4  0 mslb
endvars

Github has completed the space automatically. In fact, there is one space in front of the variable 'tslb' or 'mslb' just like the fig shows. 
![01](https://user-images.githubusercontent.com/69755697/93009758-30840480-f5b7-11ea-9867-fd40f35e4f94.png)

**Comment by miniufo** [comment]
Sorry, I forgot to check my email.  Now it is fixed for this case at [here](https://github.com/miniufo/xgrads/blob/7d288abecfca6eaf6c5bd1844e89454c701d7f4c/xgrads/core.py#L795), simply by adding `strip()` to trim all the blanks at the start and the end.  Thanks very much for finding this bug.

Please try the new code from github site (or just modify your source code slightly).  I've not update the package on pypi.

**Comment by cjj920** [comment]
solved! thank  you so much!

**Comment by miniufo** [comment]
Glad you solve it and don't forget to star this package if you like it ∩_∩.
