### ISSUE TITLE
How to read little-endian data?

### ISSUE THREAD

**Issue by cjj920** [miniufo/xgrads#18]
Hi, my output data is abnormal obviously when I read Sea Surface Temperature. then '_CtlDescriptor_' shows that it is little-endian data. Does **xgrads** read big-endian data by default? What should i do if i want to read little-endian data?
The following is my ctlfile:
> * obtained from mksst.f on 2001/07/06
> * basic state
> * derived from Shea's SST climatology
> DSET ^sstsum.grd
> * BYTESWAPPED
> OPTIONS SEQUENTIAL YREV
> TITLE BASIC STATE
> UNDEF -999.
> XDEF 64 LINEAR 0. 5.625
> YDEF 32 LEVELS -85.761 -80.269 -74.745 -69.213 -63.679 -58.143 -52.607 
> -47.070 -41.532 -35.995 -30.458 -24.920 -19.382 -13.844 -8.3067 -2.7689 
> 2.7689 8.3067 13.844 19.382 24.920 30.458 35.995 41.532 47.070 52.607 
> 58.143 63.679 69.213 74.745 80.269 85.761
> ZDEF 1  LEVELS 300
> TDEF 1 LINEAR 15jan2000 1mo
> VARS 1
> t      0 99 mean SST [K]
> ENDVARS

output from '_CtlDescriptor(file=ctl)_':
> ......
>    indxPath: 
>    stnmPath: 
>       title: BASIC
>       undef: -999.0
>        zrev: False
>        yrev: True
>       dtype: 
>    template: False
>   periodicX: True
>  cal365Days: False
>  sequential: True
>   **byteOrder: little**
> ......

and abnormal SST output:
> [[[ 1.76228614e-26  1.76228614e-26  1.76228614e-26 ...  1.76228614e-26
    1.76228614e-26  1.76228614e-26]
  [ 1.76228614e-26  1.76228614e-26  1.90864627e+09 ...  1.76228614e-26
    1.76228614e-26  1.76228614e-26]
  [-3.71253724e+24 -6.88422253e-09 -9.18673025e+34 ...  1.76228614e-26
    6.82927872e+09  2.03454761e-06]
  ...

**Comment by miniufo** [comment]
Hi, you may switch the byte order by adding or removing BYTESWAPPED in the options line.  The default behavior depends on the platform you are using.

**Comment by cjj920** [comment]
Got it! Thank you so much !
