### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by xigrug** [miniufo/xgrads#20]
> dset = open_CtlDataset('pm.ctl')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/public/software/anaconda3/lib/python3.8/site-packages/xgrads/io.py", line 102, in open_CtlDataset
>     ctl = CtlDescriptor(encoding=encoding, file=desfile)
>   File "/home/public/software/anaconda3/lib/python3.8/site-packages/xgrads/core.py", line 123, in __init__
>     if dirname[-1] != '/':
> IndexError: string index out of range

the ctl file is 
```
dset ^pmvar
options sequential
title model output from sim
undef -9.99E+33
xdef  502 linear   70.0000    0.1500
ydef  330 linear   15.0000    0.1500
zdef   51 linear 1 1
tdef   73 linear 00z14NOV2020    60mn
vars        9
bc 0 0  BC AOD
oc 0 0  OC AOD
sd 0 0  SD AOD
ss 0 0  SS AOD
sf 0 0  SF AOD
ni 0 0  NI AOD
am 0 0  AM AOD
pm25   50 99 pm25 concentration
fktm   50 99 diffusion coefficient
endvars
```

How to deal with this? Thanks

**Comment by miniufo** [comment]
Hi thanks for your try.  I'm not sure but you may have to provide the absolute path of the `ctl` file to `open_CtlDataset` like `dset = open_CtlDataset('d:/pm.ctl')` or `dset = open_CtlDataset('/public/home/somebody/pm.ctl')`.  You may give a try and tell me the result.

**Comment by xigrug** [comment]
Thanks, this is OK now!

> Hi thanks for your try. I'm not sure but you may have to provide the absolute path of the `ctl` file to `open_CtlDataset` like `dset = open_CtlDataset('d:/pm.ctl')` or `dset = open_CtlDataset('/public/home/somebody/pm.ctl')`. You may give a try and tell me the result.

**Comment by miniufo** [comment]
Glad it works.  I forgot that if you use the current directory, you may try `dset = open_CtlDataset('./pm.ctl')`.
