### ISSUE TITLE
How to locate latitude and longitude information in PDEF?

### ISSUE THREAD

**Issue by U-369956** [miniufo/xgrads#21]
Thanks for your wonderful xgrads module!
But how to locate latitude and longitude information in PDEF?

For example，I want to select 100°N，50°E in dataset , how can I do ?

Thank you!

**Comment by miniufo** [comment]
You may want to read [this notebook](https://github.com/miniufo/xgrads/blob/master/notebooks/Plot%20preprojected%20data%20defined%20in%20PDEF.ipynb).  GrADS defines Lambert data using Lambert coordinates (from 0 in unit of meter).  Xdef and ydef in ctl are used for display.  So If you want to select data at a given lat/lon pair, you have to convert the lat/lon coordinate to Lambert coordinate (x/y) and then select it using x/y coordinate.

The conversion algorithm can be found [at here](http://cola.gmu.edu/grads/gadoc/map.html#lambert).  I may try to add this functionality if I have time.

**Comment by miniufo** [comment]
I just add a function `interp_to_latlon` in `utils`.  If you want to return a variable defined on lat/lon grid, instead of preprojected coordinates (e.g., Lambert projection), you can do this:
```python
from xgrads import open_CtlDataset
from xgrads import interp_to_latlon

dset, ctl = open_CtlDataset('d:/EMI_2014_monthly.ctl', returnctl=True)

emi = interp_to_latlon(dset.emi_index, ctl)

# select first time step
emi[0].plot(figsize=(14,7), cmap='jet')

# select a point at 100°N, 50°E
station = emi.sel(dict(lon=50, lat=100))
```

Hope this helps.

**Comment by U-369956** [comment]
Solved! Thank you so much!
