### ISSUE TITLE
the lowercase brings some problem

### ISSUE THREAD

**Issue by finler** [miniufo/xgrads#22]
I have some dir was uppercase，the dset in ctl file was lowercased by the core.py , so the program can't find the data file.
Can that be fixed?
thanks!

**Comment by miniufo** [comment]
Can you provide more details?  I have some test cases in `tests` directory, some of which have upper-case paths.  All these cases passed.  More details (sample data file and ctl file) would help me find the bugs.

**Comment by finler** [comment]
哥，我发现你是中国人……
是这样的，我发现你的程序非常好用，我稍微改了下，将 ctl = CtlDescriptor(content=content)，在程序里写好了ctl信息，然后直接读数据文件，不用生成实体.ctl文件。但是读大写目录时全被转成了小写，导致数据读不到，可能是我中间出了问题吧。
请问能不能将    ctl = CtlDescriptor(content=content) ‘官方’直接接入读数据部分啊？
非常感谢！！

**Comment by miniufo** [comment]
哦，明白了，我都是用文件测试的，content用的不多，我改改先，应该不难。

**Comment by miniufo** [comment]
做了小的更新，现在可以把`CtlDescriptor`当作输入参数给`open_CtlDataset`了，比如：
```python
from xgrads import CtlDescriptor, open_CtlDataset

ctl = CtlDescriptor(content=content)
dset = open_CtlDataset(ctl)

print(dset)
```
试试看？

**Comment by finler** [comment]
感谢^_^

**Comment by miniufo** [comment]
如果没问题记得点个星给我哈，然后可以close这条问题了，谢谢。
