### ISSUE TITLE
Problem using xgrads and plotting

### ISSUE THREAD

**Issue by lauramillie** [miniufo/xgrads#23]
I am using python 3.8 and i have a problem using xgrads in a loop while creating charts.

If I am only reading the datasets, the program doesn't raise an error. However if I read the dataset and create a plot (either with .plot or with the matplotlib library) an error related to the datetime format of the .ctl file is raised in the second iteration of the loop. After creating the plot, even a simple `print(datetime.strptime('30 Nov 00', '%d %b %y'))` is not working anymore.

I tried converting my binary files in netcdf (with `open_CtlDataset('input.ctl').to_netcdf('output.nc')` ) and using them for creating the charts and a similar issue is raised. I found that if I create all the .nc files in a first loop and then creating all my charts in a second loop, the error will not be raised.

Any idea where this issue is coming from ?

**Comment by miniufo** [comment]
Could you please provide the detailed information about the error (and also the code generating it)?  If the reading doesn't raise an error, it may not be an error of the xgrads package.

**Comment by lauramillie** [comment]
For example, the code : 

```
from xgrads import open_CtlDataset
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np



print(datetime.strptime('30 Nov 00', '%d %b %y'))
dset2=open_CtlDataset('input.ctl')

variable = dset2['tair'].values
v_mean =np.mean(variable, 0)

plt.imshow(v_mean)
plt.colorbar()
plt.xlabel('longitude')
plt.ylabel('latitude')
plt.savefig('test.png')
plt.close()

print(datetime.strptime('30 Nov 00', '%d %b %y'))
```

Returns the following : 

2000-11-30 00:00:00
Traceback (most recent call last):
  File "/home/user/pycharm-community-2020.3.3/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/pycharm-community-2020.3.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user/PycharmProjects/test_env/test_xgrads.py", line 21, in <module>
    print(datetime.strptime('30 Nov 00', '%d %b %y'))
  File "/home/user/anaconda3/envs/test_env/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/user/anaconda3/envs/test_env/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '30 Nov 00' does not match format '%d %b %y'


The plot is created and saved normally, but i can not use the datetime module again (either for reading another .ctl, or just to print a date like in the code above). If i try the same code and comment all the lines starting with `plt. ` there is no error raised and both print commands work.
(sorry if it is not related to the xgrads package, I thought it might have been)

**Comment by miniufo** [comment]
Could you paste the content of the ctl file here?  I tried with your code (but using my own ctl and data file) and everything is fine.

**Comment by lauramillie** [comment]
DSET ^../../outputs/wo_assim/tair.gdat
TITLE SnowModel single-variable output file
UNDEF    -9999.0
XDEF      204 LINEAR           1.00000000          1.00000000
YDEF      133 LINEAR           1.00000000          1.00000000
#XDEF      204 LINEAR           0.00000000        500.00000000
#YDEF      133 LINEAR           0.00000000        500.00000000
#XDEF      204 LINEAR           0.00000000          0.50000000
#YDEF      133 LINEAR           0.00000000          0.50000000
#XDEF      204 LINEAR      814250.00000000        500.00000000
#YDEF      133 LINEAR     4722750.00000000        500.00000000
#XDEF      204 LINEAR         814.25000000          0.50000000
#YDEF      133 LINEAR        4722.75000000          0.50000000
ZDEF         1 LINEAR 1 1
TDEF     8784 LINEAR 00Z01sep2015  1hr
VARS     1
tair  0  0 air temperature (deg C)
ENDVARS

**Comment by miniufo** [comment]
emmm, nothing seems to be wrong.  Could you send me `tair.gdat` for further tests?  It is surprising that this could affect the `datetime` package...

**Comment by lauramillie** [comment]
Yes I agree. I also have trouble understanding this issue. I sent you the file on the email address registered on your profile since github doesn't support .gdat. Thank you very much for your help!

**Comment by miniufo** [comment]
Using your dataset and ctl file, there is no problem at all in my environment with `Python` 3.7, `xarray` 0.16.2, `numpy` 1.19.2, `matplotlib` 3.3.2. 
![image](https://user-images.githubusercontent.com/9312831/114639708-13581580-9d01-11eb-8a23-a1c6daaa9315.png)

Since you can save the plot, I may guess that it is a problem with your environment, not with `xgrads` package.

Also, using `.values` is a `numpy`-style code.  Since `xgrads` is built on top of `xarray`, I would suggest the `xarray`-style coding, which could use `dask` for lazy loading of the large dataset (~900MB).  You can try:
```python
from xgrads.xgrads import open_CtlDataset
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

print(datetime.strptime('30 Nov 00', '%d %b %y'))
dset2=open_CtlDataset('d:/tair.ctl')

variable = dset2['tair']

# v_mean is a dask array. If you want to load data
# into memory immediately, you can use `v_mean.load()`
v_mean = variable.mean('time')

# xarray's plot wrapper of matplotlib
v_mean.plot(figsize=(15,8), cmap='jet', levels=np.linspace(0,15,31))

print(datetime.strptime('30 Nov 00', '%d %b %y'))
```

**Comment by lauramillie** [comment]
Thank you very much for your help and the time you spent on my problem. I will try your suggestion!
