### ISSUE TITLE
Error while open ctl with %f2.dat

### ISSUE THREAD

**Issue by janer0** [miniufo/xgrads#25]
the ctl file is begin with 
dset ^Z_NAFP_C_BABJ_2019071512_P_CAMS-CPEFS-ASEC_%f2.dat

open ctl error 

  File "<ipython-input-8-2facb5dbaa6a>", line 1, in <module>
    ctl = CtlDescriptor(file='F:/CPEFS/Z_NAFP_C_BABJ_2019071512_P_CAMS-CPEFS-ASEC.ctl')

  File "c:\programdata\anaconda3\lib\site-packages\xgrads\core.py", line 137, in __init__
    self.parse(fileContent)

  File "c:\programdata\anaconda3\lib\site-packages\xgrads\core.py", line 181, in parse
    self._processDSets(dpath_str)

  File "c:\programdata\anaconda3\lib\site-packages\xgrads\core.py", line 205, in _processDSets
    tokens.append(self._get_template_format(token))

  File "c:\programdata\anaconda3\lib\site-packages\xgrads\core.py", line 525, in _get_template_format
    raise Exception('unsupported format: ' + part)

Exception: unsupported format: %f2

**Comment by miniufo** [comment]
Could you please provide me a sample dataset and ctl file so that I can find a solution?

**Comment by miniufo** [comment]
I received your sample data with name `Z_NAFP_C_BABJ_2019071512_P_CAMS-CPEFS-ASEC_00`.  The last `00` corresponds to `%f2`.   Could you provides more file names?  I expect to be `06`, `12`, `18`...  `Template` in ctl means a single ctl describing more than one data files.  I need to know the rules of the file names.

**Comment by janer0** [comment]
the 00 means t=0, and the next is 01,02...48, refer to tdef 49 in ctl file

**Comment by miniufo** [comment]
Actually, I've updated the code to support %f2.  See [here](https://github.com/miniufo/xgrads/blob/7b434e74d36e30a8d7ea6794f747a87d74a0c383/xgrads/core.py#L525) and you may check if you are using the newest codes.

**Comment by janer0** [comment]
yes, this code works. seems pip install is not the newest codes

**Comment by miniufo** [comment]
Ops I forgot to update that...
