### ISSUE TITLE
modify ctl？

### ISSUE THREAD

**Issue by neko007** [miniufo/xgrads#26]
请教一下是否可以读取ctl进行修改，并利用修改后的ctl进行文件读取？

**Comment by miniufo** [comment]
这是需要批量修改吗？我感觉最方便的应该是直接修改文件的内容再读。

**Comment by neko007** [comment]
我刚接触GrADS的ctl，遇到一个需要读取存储在不同年份文件夹里的逐小时数据的需求，按您这种方法需要每个年份文件夹都匹配一个ctl或者每读一个文件夹就改一次ctl。既然都可以将用CtlDescriptor解析ctl，直接修改这个解析后的对象中的时间信息，就可以直接在python里循环读取不同年份文件夹的数据了。不知道您的模块是否能实现这个功能？

**Comment by miniufo** [comment]
ctl文件里面的dset可以写完整的路径呀，然后template关键字实现不用路径（特别是时间）的多个文件的读取。[这里有不少例子：](http://cola.gmu.edu/grads/gadoc/templates.html)

**Comment by neko007** [comment]
非常感谢，刚刚入门，还需要学习学习！
