### ISSUE TITLE
Problem using function 'to_netcdf()'

### ISSUE THREAD

**Issue by douyuqi** [miniufo/xgrads#29]
Hi, I am using python 3.9 and i have a problem using xgrads to convert a GrADS dataset to a NetCDF dataset with function tp_netcdf().

The error infomation is:

OSError: [WinError 8] 内存资源不足，无法处理此命令。

Any idea?

**Comment by miniufo** [comment]
你好，可以提供dset的print信息吗？然后还有你的机器内存大小是多少？估计是你的内存不够，看看能不能调整chunk来避免这个错误。

**Comment by miniufo** [comment]
我没有看到附件哦，你可以直接贴上来的？

**Comment by douyuqi** [comment]
WARNING:&nbsp;expected&nbsp;binary&nbsp;file&nbsp;size:&nbsp;94003200,&nbsp;actual&nbsp;size:&nbsp;54835200
<xarray.Dataset&gt;
Dimensions:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(time:&nbsp;12,&nbsp;y:&nbsp;320,&nbsp;x:&nbsp;360)
Coordinates:
&nbsp;&nbsp;*&nbsp;time&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(time)&nbsp;datetime64[ns]&nbsp;2020-01-01&nbsp;2020-02-01&nbsp;...&nbsp;2020-12-01
&nbsp;&nbsp;*&nbsp;y&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(y)&nbsp;float64&nbsp;0.0&nbsp;1.5e+04&nbsp;3e+04&nbsp;...&nbsp;4.755e+06&nbsp;4.77e+06&nbsp;4.785e+06
&nbsp;&nbsp;*&nbsp;x&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(x)&nbsp;float64&nbsp;0.0&nbsp;1.5e+04&nbsp;3e+04&nbsp;...&nbsp;5.355e+06&nbsp;5.37e+06&nbsp;5.385e+06
Data&nbsp;variables:&nbsp;(12/17)
&nbsp;&nbsp;&nbsp;&nbsp;emi_index&nbsp;&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;demi_index&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;emis_index&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dep_index&nbsp;&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;diff_index&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;trans_index&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;...&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;cpt_demi&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;cpt_emis&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;cpt_in&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;cpt_dep&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;cpt_diff&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
&nbsp;&nbsp;&nbsp;&nbsp;cpt_out&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(time,&nbsp;y,&nbsp;x)&nbsp;&gt;f4&nbsp;dask.array<chunksize=(1,&nbsp;320,&nbsp;360),&nbsp;meta=np.ndarray&gt;
Attributes:
&nbsp;&nbsp;&nbsp;&nbsp;comment:&nbsp;&nbsp;pm&nbsp;&nbsp;&nbsp;1/1
&nbsp;&nbsp;&nbsp;&nbsp;storage:&nbsp;&nbsp;99
&nbsp;&nbsp;&nbsp;&nbsp;title:&nbsp;&nbsp;&nbsp;&nbsp;CUACE_emi_index
&nbsp;&nbsp;&nbsp;&nbsp;undef:&nbsp;&nbsp;&nbsp;&nbsp;-9999.0
&nbsp;&nbsp;&nbsp;&nbsp;pdef:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lcc

Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
&nbsp;&nbsp;File&nbsp;"E:\Project\河南\河南气象局\河南气象\code\BiteGrADS-f15f4cf01283c97a73f03dd7e67722a66366ecc0\GrADS.py",&nbsp;line&nbsp;10,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;dset.to_netcdf('E:\EMI_2021_monthly.nc')
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\xarray\core\dataset.py",&nbsp;line&nbsp;1900,&nbsp;in&nbsp;to_netcdf
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;to_netcdf(
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\xarray\backends\api.py",&nbsp;line&nbsp;1086,&nbsp;in&nbsp;to_netcdf
&nbsp;&nbsp;&nbsp;&nbsp;writes&nbsp;=&nbsp;writer.sync(compute=compute)
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\xarray\backends\common.py",&nbsp;line&nbsp;167,&nbsp;in&nbsp;sync
&nbsp;&nbsp;&nbsp;&nbsp;delayed_store&nbsp;=&nbsp;da.store(
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\array\core.py",&nbsp;line&nbsp;1040,&nbsp;in&nbsp;store
&nbsp;&nbsp;&nbsp;&nbsp;compute_as_if_collection(Array,&nbsp;store_dsk,&nbsp;store_keys,&nbsp;**kwargs)
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\base.py",&nbsp;line&nbsp;313,&nbsp;in&nbsp;compute_as_if_collection
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;schedule(dsk2,&nbsp;keys,&nbsp;**kwargs)
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\threaded.py",&nbsp;line&nbsp;79,&nbsp;in&nbsp;get
&nbsp;&nbsp;&nbsp;&nbsp;results&nbsp;=&nbsp;get_async(
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\local.py",&nbsp;line&nbsp;517,&nbsp;in&nbsp;get_async
&nbsp;&nbsp;&nbsp;&nbsp;raise_exception(exc,&nbsp;tb)
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\local.py",&nbsp;line&nbsp;325,&nbsp;in&nbsp;reraise
&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;exc
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\local.py",&nbsp;line&nbsp;223,&nbsp;in&nbsp;execute_task
&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;_execute_task(task,&nbsp;data)
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\core.py",&nbsp;line&nbsp;121,&nbsp;in&nbsp;_execute_task
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;func(*(_execute_task(a,&nbsp;cache)&nbsp;for&nbsp;a&nbsp;in&nbsp;args))
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\core.py",&nbsp;line&nbsp;121,&nbsp;in&nbsp;<genexpr&gt;
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;func(*(_execute_task(a,&nbsp;cache)&nbsp;for&nbsp;a&nbsp;in&nbsp;args))
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\core.py",&nbsp;line&nbsp;121,&nbsp;in&nbsp;_execute_task
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;func(*(_execute_task(a,&nbsp;cache)&nbsp;for&nbsp;a&nbsp;in&nbsp;args))
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\core.py",&nbsp;line&nbsp;121,&nbsp;in&nbsp;<genexpr&gt;
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;func(*(_execute_task(a,&nbsp;cache)&nbsp;for&nbsp;a&nbsp;in&nbsp;args))
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\core.py",&nbsp;line&nbsp;121,&nbsp;in&nbsp;_execute_task
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;func(*(_execute_task(a,&nbsp;cache)&nbsp;for&nbsp;a&nbsp;in&nbsp;args))
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\core.py",&nbsp;line&nbsp;121,&nbsp;in&nbsp;<genexpr&gt;
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;func(*(_execute_task(a,&nbsp;cache)&nbsp;for&nbsp;a&nbsp;in&nbsp;args))
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\dask\core.py",&nbsp;line&nbsp;121,&nbsp;in&nbsp;_execute_task
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;func(*(_execute_task(a,&nbsp;cache)&nbsp;for&nbsp;a&nbsp;in&nbsp;args))
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\xgrads\io.py",&nbsp;line&nbsp;448,&nbsp;in&nbsp;__read_var
&nbsp;&nbsp;&nbsp;&nbsp;data&nbsp;=&nbsp;__read_continuous(file,&nbsp;pos,&nbsp;shape,&nbsp;dtype,
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\xgrads\io.py",&nbsp;line&nbsp;492,&nbsp;in&nbsp;__read_continuous
&nbsp;&nbsp;&nbsp;&nbsp;data&nbsp;=&nbsp;np.memmap(f,&nbsp;dtype=dtype,&nbsp;mode='r',&nbsp;offset=offset,
&nbsp;&nbsp;File&nbsp;"C:\Users\douyuqi\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\memmap.py",&nbsp;line&nbsp;267,&nbsp;in&nbsp;__new__
&nbsp;&nbsp;&nbsp;&nbsp;mm&nbsp;=&nbsp;mmap.mmap(fid.fileno(),&nbsp;bytes,&nbsp;access=acc,&nbsp;offset=start)
OSError:&nbsp;[WinError&nbsp;8]&nbsp;内存资源不足，无法处理此命令。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miniufo/xgrads"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月2日(星期四) 下午4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [miniufo/xgrads] Problem using function 'to_netcdf()' (#29)





 
我没有看到附件哦，你可以直接贴上来的？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by miniufo** [comment]
我看到一句warning：expected binary file size: 94003200, actual size: 54835200，根据网格计算的数据文件大小是94MB（320*360*12*变量数*4），但是实际的数据文件只有54MB，估计数据不完整？

如果这个问题解决了还出错，可以发一份数据给我，我来调试一下。
