### ISSUE TITLE
If the globe information important in  crs= get_data_projection(ctl)?

### ISSUE THREAD

**Issue by singledoggy** [miniufo/xgrads#32]
get_data_projection(ctl) set the default `ccrs.Globe` as `ellps=WGS84`, but actually in WRF-model or other weather model, the earth is considered as sphere like. To get the accurate shape, we sometimes need to set:
````
globe = ccrs.Globe(ellipse='sphere', semimajor_axis=6370000,
                   semiminor_axis=6370000)
````
There maybe some way to change ccrs after a `catropy.ccrs` is created, but it may not that convenient to do so. 
Thanks again for your excellent work!

**Comment by miniufo** [comment]
I am not familiar with this details.  I think this is not related to the package itself (plot functionality).  But I would like to know this.  Would you please show the difference (maybe by plotting some data) between the default setting and the one used in weather models?
BTW, I added `get_data_projection` in `utils.py` to facilitate plotting of pdef data.  If you are more familiar with the plotting of pdef, do you think this is the best design?  I guess `GrADS`'s first interpolating to lat/lon grid and then plotting is not straightforward.

**Comment by singledoggy** [comment]
Here is a blog introduce the difference of sphere and WGS84 earth.
https://fabienmaussion.info/2018/01/06/wrf-projection/

 **Bascally when resolution is low it has no influence.**  `crs ` information provides a way to change PCS(ProjectedCoordinate System) to GCS(GeographicCoordinate System), and 
Here is a blog introduce the difference.
https://blog.sciencenet.cn/blog-290812-1016263.html

Basically, when the `globe` is different, the map function between PCS and GCS would be different. PDF did't point out the globe information, so we may need to set by ourselves. 

I use this tool to get a projection information, and I don't interpolating it.  In your example  you didn't interpolate too, I think it's better. 

It's quite trivial, and maybe it's not that important in many cases. And I don't know if anyone need this information. Maybe it's irrelavation with your tool. But if anyone need, the can change it by themselves qucikly. 

Thanks for your quick responding!

**Comment by miniufo** [comment]
Thanks for all the detailed links to clarify this.  After reading all these, I think you are right, providing a kwarg like `earth_radius` would be more flexible.  I guess the root of the problem is that WRF uses a radius (6370km) that is somewhat different from the one used in `cartopy`.  It is interesting to note that `GrADS` uses 6371.2km...

I think I'll set the defaut to 6371.2km, in accordance with GrADS.  If one use WRF data, it is then his/her responsibility to change the default radius.

Do you think this is OK?

**Comment by singledoggy** [comment]
`GrADS` uses `6371.2km` is interesting.  Maybe in that time the data resolution was low so it's not important . Thanks for your information and responding. You're right, users who cares about it should set by themselve.
