### ISSUE TITLE
there are missing binary files

### ISSUE THREAD

**Issue by JQQQQQQ** [miniufo/xgrads#39]
Hello, I follow your modification after the operation reported the following error。My binary data file is from 00 hours to 24 hours. Please help me, thank you!

Traceback (most recent call last):
File "F:/python/CUACE/test20161216.py", line 3, in
fn=open_CtlDataset('G:/CUACE/result/0907/chemvar.ctl')
File "D:\soft\Anaconda\lib\site-packages\xgrads\io.py", line 143, in open_CtlDataset
raise Exception('there are missing binary files')
Exception: there are missing binary files
warning: G:/CUACE/result/0907/chemvar201612160002500 is missing...

**Comment by miniufo** [comment]
Sorry I missed your post.  Could you please show me the ctl content and also all your data files (names only)?  I guess your tdef is longer than the actual data length.

**Comment by tsumeten** [comment]
您好，我也遇到了同样的问题
 warning: ./hs_no3..%y4 is missing...
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[6], line 3
      1 # print all the info in ctl file
      2 from xgrads import open_CtlDataset
----> 3 DDDD=open_CtlDataset('hs_no3.ctl')
      4 print(DDDD)

File ~/miniconda3/lib/python3.12/site-packages/xgrads/io.py:137, in open_CtlDataset(desfile, returnctl, encoding)
    134         has_missing = True
    136 if has_missing:
--> 137     raise Exception('there are missing binary files')
    139 total_size = sum(tcPerf)
    141 if total_size < tcount:

Exception: there are missing binary files
其中ctl内容是这样的
DSET ^hs_no3.%y4
OPTIONS template big_endian
TITLE Nitrate (mean_lfam3_2nd)
UNDEF -0.9990000E+34
XDEF    62 LEVELS
   -1.00000    0.00000    1.00000    2.00000    3.00000
    4.00000    5.00000    6.00000    7.00000    8.00000
    9.00000   10.00000   11.00000   12.00000   13.00000
   14.00000   15.00000   16.00000   17.00000   18.00000
   19.00000   20.00000   21.00000   22.00000   23.00000
   24.00000   25.00000   26.00000   27.00000   28.00000
   29.00000   30.00000   31.00000   32.00000   33.00000
   34.00000   35.00000   36.00000   37.00000   38.00000
   39.00000   40.00000   41.00000   42.00000   43.00000
   44.00000   45.00000   46.00000   47.00000   48.00000
   49.00000   50.00000   51.00000   52.00000   53.00000
   54.00000   55.00000   56.00000   57.00000   58.00000
   59.00000   60.00000
YDEF    52 LEVELS
    9.00000   10.00000   11.00000   12.00000   13.00000
   14.00000   15.00000   16.00000   17.00000   18.00000
   19.00000   20.00000   21.00000   22.00000   23.00000
   24.00000   25.00000   26.00000   27.00000   28.00000
   29.00000   30.00000   31.00000   32.00000   33.00000
   34.00000   35.00000   36.00000   37.00000   38.00000
   39.00000   40.00000   41.00000   42.00000   43.00000
   44.00000   45.00000   46.00000   47.00000   48.00000
   49.00000   50.00000   51.00000   52.00000   53.00000
   54.00000   55.00000   56.00000   57.00000   58.00000
   59.00000   60.00000
ZDEF    10 LEVELS
   10.00000   35.00000   75.00000  150.00000  300.00000
  500.00000  800.00000 1500.00000 3000.00000 5000.00000
TDEF    10 LINEAR  23:00Z01JAN1901 1DY
VARS    1
  no3 10 99 Dissolved_nitrate_concentration [mol m-3]
ENDVARS
文件目录中包含二进制文件才对，不知道为何还会报错，求解，谢谢
![Image](https://github.com/user-attachments/assets/2d8dae21-3efa-4a53-871d-66881f2cb989)

**Comment by miniufo** [comment]
代码在解析路径时确实有bug，感谢report。

当下简单的方法就是不用template，直接给年份：DSET ^hs_no3.1901。因为一个文件一年，远超10天。

这里的文件命名规则和我预期的不一样，但也是合理的。所以我需要点时间修改解析文件的路径。不知道你是否需要打开很多不同年份的文件？

**Comment by tsumeten** [comment]
您说的方法我昨天也尝试过了，但貌似将ctl的文件修改成如下格式后又产生了新的bug
```
DSET ^hs_no3.1901
OPTIONS template big_endian
TITLE Nitrate (mean_lfam3_2nd)
UNDEF -0.9990000E+34
XDEF    62 LEVELS
   -1.00000    0.00000    1.00000    2.00000    3.00000
    4.00000    5.00000    6.00000    7.00000    8.00000
    9.00000   10.00000   11.00000   12.00000   13.00000
   14.00000   15.00000   16.00000   17.00000   18.00000
   19.00000   20.00000   21.00000   22.00000   23.00000
   24.00000   25.00000   26.00000   27.00000   28.00000
   29.00000   30.00000   31.00000   32.00000   33.00000
   34.00000   35.00000   36.00000   37.00000   38.00000
   39.00000   40.00000   41.00000   42.00000   43.00000
   44.00000   45.00000   46.00000   47.00000   48.00000
   49.00000   50.00000   51.00000   52.00000   53.00000
   54.00000   55.00000   56.00000   57.00000   58.00000
   59.00000   60.00000
YDEF    52 LEVELS
    9.00000   10.00000   11.00000   12.00000   13.00000
   14.00000   15.00000   16.00000   17.00000   18.00000
   19.00000   20.00000   21.00000   22.00000   23.00000
   24.00000   25.00000   26.00000   27.00000   28.00000
   29.00000   30.00000   31.00000   32.00000   33.00000
   34.00000   35.00000   36.00000   37.00000   38.00000
   39.00000   40.00000   41.00000   42.00000   43.00000
   44.00000   45.00000   46.00000   47.00000   48.00000
   49.00000   50.00000   51.00000   52.00000   53.00000
   54.00000   55.00000   56.00000   57.00000   58.00000
   59.00000   60.00000
ZDEF    10 LEVELS
   10.00000   35.00000   75.00000  150.00000  300.00000
  500.00000  800.00000 1500.00000 3000.00000 5000.00000
TDEF    10 LINEAR  23:00Z01JAN1901 1DY
VARS    1
  no3 10 99 Dissolved_nitrate_concentration [mol m-3]
ENDVARS
```
![Image](https://github.com/user-attachments/assets/d2654b29-1516-4fe5-9f6a-f0bbb63846de)

**Comment by miniufo** [comment]
你改名后需要把OPTIONS里面的template去掉，英文路径里面没有%号了

**Comment by tsumeten** [comment]
感谢帮助，目前可以成功转化为nc文件了，但是仍会弹出警告

![Image](https://github.com/user-attachments/assets/78ace1e3-6e3a-40ad-96fa-6ec237e0928b)

我用panoly查看了hs_ssh.ctl(海平面高度)转化的nc文件，结果看起来好像出错了

![Image](https://github.com/user-attachments/assets/19393ebe-5b27-4c96-9c7e-e387c212b6d5)

![Image](https://github.com/user-attachments/assets/6fdffc39-5098-4c55-9b7e-c30f6188979a)

实际上如果用grads打开的ctl的话是这样的

![Image](https://github.com/user-attachments/assets/d971400d-0bea-4707-867f-2aac4aaecb17)

**Comment by miniufo** [comment]
你用open_CtlDataset('hs_sst.ctl').ssh.plot()看看能不能正常画图，能画图再转nc试试

**Comment by miniufo** [comment]
我刚刚更新了代码，你用原来的含有百分号的路径应该也能解析了。如果方便可以帮忙测试一下，感谢

**Comment by tsumeten** [comment]
感谢回复，目前新的代码可以解析含有年份的数据了，但是我在将数据转换为nc文件还是存在问题，我也尝试用其他包对该数据处理了，结果还是很奇怪，所以应该不是您的代码问题。我再确认一下数据，再次感谢您的帮助！

**Comment by miniufo** [comment]
如果方便，你可以发一份数据（包含ctl）给我，miniufo@163.com，如果Grads可以画图，理论上xgrads就能正常转nc，我也想知道是不是有我没考虑的问题。
