### ISSUE TITLE
Don't support .ctl containing EDEF description

### ISSUE THREAD

**Issue by Milton-yu** [miniufo/xgrads#42]
DSET ^ecmf_medium_10m_uv-component_of_wind.dat
TITLE ENSEMBLE DATA
UNDEF 9.999E20
XDEF 161 LINEAR 70.0000 0.500000
YDEF 111 LINEAR 0.000000 0.500000
ZDEF 1 LEVELS -9999.0
TDEF 41 LINEAR 00Z01Jan2021 6hr
EDEF 51 NAMES c00 p01 p02 p03 p04 p05 p06 p07 p08 p09 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30 p31 p32 p33 p34 p35 p36 p37 p38 p39 p40 p41 p42 p43 p44 p45 p46 p47 p48 p49 p50
VARS 2
u10 0 99 10 metre U wind component
v10 0 99 10 metre V wind component
ENDVARS

When use "CtlDescriptor"  to show the descriptions,
e.g ctl = CtlDescriptor(file='C:/Temp/ECEN/2021010100/ecmf_medium_10m_uv-component_of_wind.ctl')
print(ctl)
there is no edef printed out.

When use "ds.to_netcdf('lst.nc')", there is only one of ensemble member transfered into nc format.

Thanks for your attention.

**Comment by miniufo** [comment]
Hi, you are right.  I haven't used such ensemble data but would like to add support to that.  Could you please send me a minimum amount of such data (through email)?  Maybe 2 or 3 ensemble files so that I can test this with real data.

**Comment by Milton-yu** [comment]
Thanks a lot for your attention. I am going to send you the real-data instance files through email, unluckly I recieved the rejecting for your poor Git email inbox space. Could you give me another way I can send your files?&nbsp; :)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miniufo/xgrads"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [miniufo/xgrads] Don't support .ctl containing EDEF description (Issue #42)





 
Hi, you are right.  I haven't used such ensemble data but would like to add support to that.  Could you please send me a minimum amount of such data (through email)?  Maybe 2 or 3 ensemble files so that I can test this with real data.

**Comment by miniufo** [comment]
It is finished now, but more tests are needed.
