### ISSUE TITLE
Add conda installation support

### ISSUE THREAD

**Issue by jypeter** [miniufo/xgrads#46]
I have tried to install `xgrads` with `conda` (with mamba `actually`) and I got a `nothing provides requested xgrads` error message 

I then had a look at the `xgrads` GH page and found out that you currently can only use `pip install xgrads`. The `pip` installation worked

You may want to:
- add a section about _installation_ to your nice documentation
- consider providing a way to install with `conda`

**Comment by miniufo** [comment]
Yes I do want to.  I've tried twice but I failed somehow (do not remember now).  Can you send me a (step by step) tutorial about how to do this?

**Comment by jypeter** [comment]
Unfortunately, I have absolutely no idea how this is done!

I only maintain a python distribution in our lab with [lots of different packages](https://wiki.lsce.ipsl.fr/pmip3/doku.php/other:uvcdat:cdat_conda:cdat_8_2_1#extra_packages_list) coming from [conda-forge](https://conda-forge.org/). _Lots_ means I have to use `mamba` instead of `conda` for installation. Otherwise `conda` can't solve the depencies and gets stuck

**Comment by miniufo** [comment]
It is now added to the [conda-forge here](https://anaconda.org/conda-forge/xgrads).  Closing this issue.  Thanks @jypeter.

**Comment by jypeter** [comment]
Thanks @miniufo !

For the record, everything went perfectly well when I uninstalled the _pip_ version, and then installed the _conda-forge_ version instead

```
 >conda list | grep -i grads
xgrads                    0.2.3                    pypi_0    pypi

 >pip uninstall xgrads
Found existing installation: xgrads 0.2.3
Uninstalling xgrads-0.2.3:
  Would remove:
    /home/share/unix_files/cdat/miniconda3_21-02/envs/cdatm19_nompi_py3/lib/python3.8/site-packages/xgrads-0.2.3.dist-info/*
    /home/share/unix_files/cdat/miniconda3_21-02/envs/cdatm19_nompi_py3/lib/python3.8/site-packages/xgrads/*
Proceed (Y/n)? Y
  Successfully uninstalled xgrads-0.2.3

>conda list | grep -i grads

 >mamba install xgrads

[...]
Looking for: ['xgrads']

pkgs/main/noarch                                              No change
pkgs/r/linux-64                                      1.5MB @   2.8MB/s  0.7s
pkgs/r/noarch                                        1.3MB @   1.5MB/s  0.7s
pkgs/main/linux-64                                   6.1MB @   3.5MB/s  2.0s
conda-forge/noarch                                  14.0MB @   3.9MB/s  4.2s
conda-forge/linux-64                                34.4MB @   4.0MB/s 10.1s

Pinned packages:
  - python 3.8.*


Transaction

  Prefix: /home/share/unix_files/cdat/miniconda3_21-02/envs/cdatm_py3

  Updating specs:

   - xgrads
   - ca-certificates
   - certifi
   - openssl


  Package   Version  Build         Channel                Size
────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────

  + xgrads    0.2.6  pyhd8ed1ab_0  conda-forge/noarch     26kB

  Summary:

  Install: 1 packages

  Total download: 26kB

────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] Y
xgrads                                              26.2kB @ 109.1kB/s  0.2s
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

 >conda list | grep -i grads
xgrads                    0.2.6              pyhd8ed1ab_0    conda-forge
```
