### ISSUE TITLE
缺测值该如何处理

### ISSUE THREAD

**Issue by jack1234lee** [miniufo/xgrads#52]
您好，我使用了open_CtlDataset将ctl转换为二进制xarray文件，可是在转换过程中缺测值被处理成了-9999，以至于绘图出现错误，请问缺测值该如何处理呢

**Comment by miniufo** [comment]
你好，你的ctl里面有缺测值的，程序会根据ctl的缺测值来赋值，你可以用函数来替换-9999为nan，如
```python
data2 = np.where(data==-9999, np.nan, data)
```

**Comment by jack1234lee** [comment]
非常感谢！
