### ISSUE TITLE
open multiple ctl files

### ISSUE THREAD

**Issue by miniufo** [miniufo/xgrads#9]
Although multiple binary data files can be described by a single `.ctl` file using [**template**](http://cola.gmu.edu/grads/gadoc/templates.html) keyword, sometimes one may need to deal with multiple `.ctl` files and corresponding multiple `.dat` files.  So I think it would be convenient to add a method `open_mfdataset('./test/*.ctl')`, which is similar to `xarray.open_mfdataset('*.nc')`, for dealing with multiple `.ctl` and binary files in consecutive times.  This may not be too complicated using `xarray.concat`.

**Comment by miniufo** [comment]
It is done now.  Please see [here](https://github.com/miniufo/xgrads/blob/b9cb1b44dff6d06bbc71a6e2fdb6f01824aa5112/xgrads/io.py#L21)

**Comment by onnyyonn** [comment]
It seems the version published at PyPI doesn't have it yet. Can you please release a new version?

**Comment by miniufo** [comment]
Hi, the latest [PyPI version](https://pypi.org/project/xgrads/) is 0.2.0, which is released on Jun 22, 2022.  The support of `template` should be already included in this version.
